sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf dpdd.pdf --upload --lsstdoc dpdd.tex --env=travis --ltd-product lse-163"
env:
  global:
    # LSST the Docs credentials
    - secure: "M2z9x6vZZhP+U75ZeMdrh3UExP79DdEhr+YLe3g19R/i3gTWBtvmVtDSHFvZLUy2yXSGiJHXN+akTjI3pBjGA/MV9DCMiYxkpZioPjOmtQB5tWrJp2d3Z/qpQB+gNxcTXcitW8OXrfb1ysl8XbSNic+FekT+7F58CJtJRhQ3jrydFZTZU+MDdS1BvLiuiX4qU6GwBHIHwvz9cqk63aUc4/pj5J/Sc6pxz2SW1I0xH3D+VgcX8EJbX30naLy58Dv+Db0j9c7u1VPvgpMIXQrxcXuZugBEo7EME/ARQiIJLmRFS+9BAG0u1bDx81ocgcBNVc0mG5khFBExobi0a0XHI1ZlFkXaGvO8M7/ADq2JzJaqhz/71HitdqegInHBmvH+vUM9KPfvhD+c6Y6nbmucINypu6/qMSoPh5cwTRNsUDu3jJnH639efnGDX/rNCP1JD7eXiZm90e+pKEdGZorG8JUuaMhVwXnYlrJ7oShNM8qdu20x/ZlDznzmk6CnD9/54otS7/bH/PcJcHFoeTOtYFuJ+dV1Prnrd97VXAaO0HPw3OpQ0RSslaNnuOtt7IKZhZ9B1KLWWYnKWMlkIYwjIXgRtGLfHpsrmZ+Fpy7ED4UYV6O+K3B+OGkBhCNMZt689RlRzLO4OU+q9WE/AUIZJc78jN5iUsMfd1QvP8nf/VU="
    - secure: "vtmqb7zX/E5gu7dlV7HE2AzRqkHrs86+wDqO8SUGQzwi7KX98NByhSlYHEwda4CbrSpy6rI1O/9I2xNeWLz2pjWZB53pLX1QCejuJoubF9wUrSHygBKb89OSS+nMErNo+rBCB1E7V6YjFsZyG0DR2Xkt8ZX53Bc3aYmGaE6AprxckytS5bFh7YvJ0dct49N/FRaCaveRMB0bU7YP+RhvMAHow4m+rV+H+36B3dWW4pWmJB80h1JGUMTmbxWKTI0uiQkOfA2zR74w52f1Hg0+KGSIGyMt9FEpcMNR3cGQ1ymVoka7qcyY58Kmxh2tCsXdqygfpVpNlHNex5jCqIUg/SYPvaShbGXGh2J9GdZ1SBuTL05yaaW5sQSMBFKF530DY55MLaEtJ71ELEudwpn4iHfTJkxULNU4U4fvVagd7NdfE0gWHciVmyuoxkb4kfyH0Qv1NtTs/MAr6Z1ykT8ZECevw3474Pwma+aKcUUwD9cE8Ipk6WpMjcd9uZuZmGfSYTdxPp1WPdOIb49L53yey3unjb4HGEWXl31t3zCKLyj8sW5xpybRsoLahzlKC2JqfV9skokinYu0lgUpIcHFQH56iKWRtNWdRudTFH5yBTP8pYIvizvJPQqveRAmf5TUmFhXKzAGhzVPVpzjlevI/t/21pqS0RFg5bTmPd9BXGM="
